name: Build

on:
  push:
    tags:
      - '*.*.*'
      - '*.*'

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
      - name: Build 5.x
        run: |
          $BUILD_DIR = "Sophia Script v"
          if ($env:GITHUB_REF -eq "refs/heads/master")
          {
            $BUILD_DIR += "master"
          }
          else
          {
            $BUILD_DIR += ${env:GITHUB_REF} -replace "refs/tags/", ""
          }

          $ZIP = "$BUILD_DIR.zip"

          New-Item -Path $BUILD_DIR -ItemType Directory -Force

          Write-Host $BUILD_DIR
          Write-Host $ZIP

          Copy-Item -Path "Sophia\PowerShell 5.1\*" -Destination $BUILD_DIR -Recurse -Force
          Copy-Item -Path "syspin\syspin.exe" -Destination $BUILD_DIR -Force
   
          Compress-Archive -Path $BUILD_DIR -DestinationPath $ZIP -Force

      - name: Build 7.x
        run: |
          $BUILD_DIR = "Sophia Script v"
          if ($env:GITHUB_REF -eq "refs/heads/master")
          {
            $BUILD_DIR += "master"
          }
          else
          {
            $BUILD_DIR += ${env:GITHUB_REF} -replace "refs/tags/", ""
          }
          $BUILD_DIR += " PS7.x"

          $ZIP = "$BUILD_DIR.zip"

          New-Item -Path $BUILD_DIR -ItemType Directory -Force

          Write-Host $BUILD_DIR
          Write-Host $ZIP

          Copy-Item -Path "Sophia\PowerShell 5.1\*" -Destination $BUILD_DIR -Recurse -Force
          Copy-Item -Path "Sophia\PowerShell 7.x\*" -Destination $BUILD_DIR -Recurse -Force
          Copy-Item -Path "syspin\syspin.exe" -Destination $BUILD_DIR -Recurse -Force

          Compress-Archive -Path $BUILD_DIR -DestinationPath $ZIP -Force

      - name: Build LTSC
        run: |
          $BUILD_DIR = "Sophia Script LTSC v"
          $ModuleVersion = (Import-PowerShellDataFile -Path "Sophia\LTSC\Sophia.psd1").ModuleVersion
          Write-Host $ModuleVersion
          $BUILD_DIR += $ModuleVersion

          $ZIP = "$BUILD_DIR.zip"

          New-Item -Path $BUILD_DIR -ItemType Directory -Force

          Write-Host $BUILD_DIR
          Write-Host $ZIP

          Copy-Item -Path "Sophia\LTSC\*" -Destination $BUILD_DIR -Recurse -Force

          Compress-Archive -Path $BUILD_DIR -DestinationPath $ZIP -Force

      - name: Wrapper
        run: |
          $BUILD_DIR = "Sophia Script Wrapper"
          $ZIP = "$BUILD_DIR.zip"

          New-Item -Path $BUILD_DIR -ItemType Directory -Force

          Write-Host $BUILD_DIR
          Write-Host $ZIP

          Copy-Item -Path "Wrapper\*" -Destination $BUILD_DIR -Recurse -Force
          Compress-Archive -Path $BUILD_DIR -DestinationPath $ZIP -Force

      - name: Upload archives to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Sophia*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          prerelease: true
 
